language: ruby
rvm:
  - 2.5.3
  - 2.4.1
  - 2.3.4
  - 2.2.7
env:
  - TESTOPTS=-v
matrix:
  include:
    - rvm: 2.5.3
      gemfile: Gemfile

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

#before_install:
# - sudo apt-get update
# - sudo apt-get install libxml2-dev libexpat1-dev

# whitelist branches
branches:
  only:
    - master
